# DEV Compose file.
# For a production file see: README.md

version: '3.7'

services:
  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379

  app:
    build: .
    depends_on:
      - redis
    environment:
      SIZE_LIMIT: 128M
    ports:
      - 80:5000
