version: '3.8'

services:
  redis:
    image: redis:7-alpine

  app:
    image: cupcakearmy/cryptgeon:latest
    depends_on:
      - redis
    
  proxy:
    image: nginx:alpine
    depends_on:
      - app
    volumes:
      - ./nginx-plain.conf:/etc/nginx/conf.d/default.conf
      # Or with tls
      # - ./nginx-tls.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
